name: cashark
description: Cashark — colorful casino roulette and space shooter rewards app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.3.1
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
